### ISSUE TITLE
Add Moonshot support

### ISSUE THREAD

**Issue by ix-56h** [franco-bianco/sol-swap-parse#1]
Hi there,

Are you planning to support the moonshot swap? I'm in the process of trying to add it and was wondering if you had any tips to share.

Thanks.

**Comment by franco-bianco** [comment]
> Hi there,
> 
> 
> 
> Are you planning to support the moonshot swap? I'm in the process of trying to add it and was wondering if you had any tips to share.
> 
> 
> 
> Thanks.

Hi

I'll have it added within the next 12 hours. 

Thank you

**Comment by franco-bianco** [comment]
I've added Moonshot support and will be closing the issue. 

The parsing of Instruction Data works similarly to the parsing of Event Data

```go
	err = decoder.Decode(&instructionData)
	if err != nil {
		return nil, fmt.Errorf("error unmarshaling moonshot buy data: %s", err)
	}
```
You will need to decode it into the **exact** type as shown below:
```go
type MoonshotTradeInstruction struct {
	Data *MoonshotTradeParams
}

type MoonshotTradeParams struct {
	TokenAmount      uint64
	CollateralAmount uint64
	FixedSide        uint8
	SlippageBps      uint64
}
```
To get this exact type, you can use [Anchor Go](https://github.com/gagliardetto/anchor-go). I've used the types there and just hardcoded it into my project with a different name so I don't have to upload all the bindings. Hope this helps!
