### ISSUE TITLE
Moonshot buy wrong amount

### ISSUE THREAD

**Issue by ix-56h** [franco-bianco/sol-swap-parse#5]
Hi !

I've found this moonshot swap : 
https://solscan.io/tx/3JBWhNdZASNHR4EUD3SNQ4XpVTWCHj4ymf6c1UALcX2MVnNiv5WMU2s9MeyszVGVLSH9fGEzgWdy2UMBcRf3QHu5

Should return : `12831491952182388` 
Current result : `13166521664831978`

It work for the sell operation : 
https://solscan.io/tx/55ciAGh4Q8XFXDqqkn9sRHE3e68WqfxxQkHJQhvJMh1CUT7GnLFxsWFFjd3agp6joTocJLmmBr1icHuGremuWKio
Correctly return `12831491952182388`

**Comment by franco-bianco** [comment]
I've looked into the discrepancy and this might be due to slippage. The buy/sell output value is currently obtained from the instruction data as shown, however the amount transferred was different. I'll add an additional check to ensure this doesn't happen
```json
{
  "data": {
    "type": {
      "defined": "TradeParams"
    },
    "data": {
      "tokenAmount": {
        "type": "u64",
        "data": "13166521664831978"
      },
      "collateralAmount": {
        "type": "u64",
        "data": "500000000"
      },
      "fixedSide": {
        "type": "u8",
        "data": 0
      },
      "slippageBps": {
        "type": "u64",
        "data": "4000"
      }
    }
  }
}
```

**Comment by franco-bianco** [comment]
I've just implemented the check as mentioned, and we'll now cross reference the token out amount against the token balance changes to take into consideration slippage and get a more accurate result. Feel free to test it and let me know if there are other issues with Moonshot

```json
[
  {
    "Type": "Moonshot",
    "Data": {
      "Instruction": {
        "Data": {
          "TokenAmount": 12831491952182387,
          "CollateralAmount": 500000000,
          "FixedSide": 0,
          "SlippageBps": 4000
        }
      },
      "Mint": "DpMLA26VeRiGRf3mSU3nA7yQ2Qxq4nXVoH1jYcLZM8Tb",
      "TradeType": 0
    }
  }
]
{
  "Signers": [
    "BTiWFDRD67apujF1uS2vXsfNoHWouPiituU2oZguuwAp"
  ],
  "Signatures": [
    "3JBWhNdZASNHR4EUD3SNQ4XpVTWCHj4ymf6c1UALcX2MVnNiv5WMU2s9MeyszVGVLSH9fGEzgWdy2UMBcRf3QHu5"
  ],
  "AMMs": [
    "Moonshot"
  ],
  "Timestamp": "0001-01-01T00:00:00Z",
  "TokenInMint": "So11111111111111111111111111111111111111112",
  "TokenInAmount": 500000000,
  "TokenInDecimals": 9,
  "TokenOutMint": "DpMLA26VeRiGRf3mSU3nA7yQ2Qxq4nXVoH1jYcLZM8Tb",
  "TokenOutAmount": 12831491952182387,
  "TokenOutDecimals": 9
}
```

**Comment by ix-56h** [comment]
Well, this is great !
But it seems that the sell swaps are broken now, the `TokenInAmount` is always 0 :

 
3UoKWbCGpsyVBwUFESXmiWhWZ5DHLUSy83ppSEBBnSYBnKNXXbwoqge23PC8QNKqQd6cLsv8t9YvoV3asUeBznM
```
{
  "Signers": [
    "5hGBAihueQdQYM14uMQDzmGVFjkgHkxA2MfPw8raj8Rc"
  ],
  "Signatures": [
    "3UoKWbCGpsyVBwUFESXmiWhWZ5DHLUSy83ppSEBBnSYBnKNXXbwoqge23PC8QNKqQd6cLsv8t9YvoV3asUeBznM"
  ],
  "AMMs": [
    "Moonshot"
  ],
  "Timestamp": "0001-01-01T00:00:00Z",
  "TokenInMint": "DYFZppXEHyKfiYG5H54apG1fMHTj2VAiRuu7iSkHyRkR",
  "TokenInAmount": 0,
  "TokenInDecimals": 9,
  "TokenOutMint": "So11111111111111111111111111111111111111112",
  "TokenOutAmount": 2072883683,
  "TokenOutDecimals": 9
}
```

Example 2: 
```
{
  "Signers": [
    "4k8WHszi2uBzTiypTKUYH1hzYkUBCARPPn6ZjPNMhDoc"
  ],
  "Signatures": [
    "2XYu86VrUXiwNNj8WvngcXGytrCsSrpay69Rt3XBz9YZvCQcZJLjvDfh9UWETFtFW47vi4xG2CkiarRJwSe6VekE"
  ],
  "AMMs": [
    "Moonshot"
  ],
  "Timestamp": "0001-01-01T00:00:00Z",
  "TokenInMint": "CQn88snXCipTxn6DBbwgSA7d9v1sXPmyxzCNNiVNXzFy",
  "TokenInAmount": 0,
  "TokenInDecimals": 9,
  "TokenOutMint": "So11111111111111111111111111111111111111112",
  "TokenOutAmount": 1761102483,
  "TokenOutDecimals": 9
}
```

**Comment by franco-bianco** [comment]
> Well, this is great ! But it seems that the sell swaps are broken now, the `TokenInAmount` is always 0 :
> 
> 3UoKWbCGpsyVBwUFESXmiWhWZ5DHLUSy83ppSEBBnSYBnKNXXbwoqge23PC8QNKqQd6cLsv8t9YvoV3asUeBznM
> 
> ```
> {
>   "Signers": [
>     "5hGBAihueQdQYM14uMQDzmGVFjkgHkxA2MfPw8raj8Rc"
>   ],
>   "Signatures": [
>     "3UoKWbCGpsyVBwUFESXmiWhWZ5DHLUSy83ppSEBBnSYBnKNXXbwoqge23PC8QNKqQd6cLsv8t9YvoV3asUeBznM"
>   ],
>   "AMMs": [
>     "Moonshot"
>   ],
>   "Timestamp": "0001-01-01T00:00:00Z",
>   "TokenInMint": "DYFZppXEHyKfiYG5H54apG1fMHTj2VAiRuu7iSkHyRkR",
>   "TokenInAmount": 0,
>   "TokenInDecimals": 9,
>   "TokenOutMint": "So11111111111111111111111111111111111111112",
>   "TokenOutAmount": 2072883683,
>   "TokenOutDecimals": 9
> }
> ```
> 
> Example 2:
> 
> ```
> {
>   "Signers": [
>     "4k8WHszi2uBzTiypTKUYH1hzYkUBCARPPn6ZjPNMhDoc"
>   ],
>   "Signatures": [
>     "2XYu86VrUXiwNNj8WvngcXGytrCsSrpay69Rt3XBz9YZvCQcZJLjvDfh9UWETFtFW47vi4xG2CkiarRJwSe6VekE"
>   ],
>   "AMMs": [
>     "Moonshot"
>   ],
>   "Timestamp": "0001-01-01T00:00:00Z",
>   "TokenInMint": "CQn88snXCipTxn6DBbwgSA7d9v1sXPmyxzCNNiVNXzFy",
>   "TokenInAmount": 0,
>   "TokenInDecimals": 9,
>   "TokenOutMint": "So11111111111111111111111111111111111111112",
>   "TokenOutAmount": 1761102483,
>   "TokenOutDecimals": 9
> }
> ```

Hi, I just pushed a fix and it works now, as shown below. I had forgotten to take into consideration the sell side of the swap, which was why the token out amount was overwritten as 0. I've made further improvements to consider the token balance change for the specific token account too, let me know if there are anymore issues!

```json
{
  "Signers": [
    "5hGBAihueQdQYM14uMQDzmGVFjkgHkxA2MfPw8raj8Rc"
  ],
  "Signatures": [
    "3UoKWbCGpsyVBwUFESXmiWhWZ5DHLUSy83ppSEBBnSYBnKNXXbwoqge23PC8QNKqQd6cLsv8t9YvoV3asUeBznM"
  ],
  "AMMs": [
    "Moonshot"
  ],
  "Timestamp": "0001-01-01T00:00:00Z",
  "TokenInMint": "So11111111111111111111111111111111111111112",
  "TokenInAmount": 34827479663161711,
  "TokenInDecimals": 9,
  "TokenOutMint": "So11111111111111111111111111111111111111112",
  "TokenOutAmount": 2052099847,
  "TokenOutDecimals": 9
}
```

```json
{
  "Signers": [
    "4k8WHszi2uBzTiypTKUYH1hzYkUBCARPPn6ZjPNMhDoc"
  ],
  "Signatures": [
    "2XYu86VrUXiwNNj8WvngcXGytrCsSrpay69Rt3XBz9YZvCQcZJLjvDfh9UWETFtFW47vi4xG2CkiarRJwSe6VekE"
  ],
  "AMMs": [
    "Moonshot"
  ],
  "Timestamp": "0001-01-01T00:00:00Z",
  "TokenInMint": "So11111111111111111111111111111111111111112",
  "TokenInAmount": 59948049312246101,
  "TokenInDecimals": 9,
  "TokenOutMint": "So11111111111111111111111111111111111111112",
  "TokenOutAmount": 1711486459,
  "TokenOutDecimals": 9
}
```
